"""empty message

Revision ID: 00ea55d12466
Revises: 4726e426ddec
Create Date: 2023-02-27 16:36:05.450479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ea55d12466'
down_revision = '4726e426ddec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corps',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('max_temp', sa.Integer(), nullable=True),
    sa.Column('min_temp', sa.Integer(), nullable=True),
    sa.Column('max_hum', sa.Integer(), nullable=True),
    sa.Column('min_hum', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('corps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corps', sa.VARCHAR(length=120), nullable=True))

    op.drop_table('corps')
    # ### end Alembic commands ###
