"""empty message

Revision ID: 02144a11c401
Revises: d3078c36003b
Create Date: 2023-02-20 10:49:00.134040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02144a11c401'
down_revision = 'd3078c36003b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('island_map', sa.String(length=100), nullable=True))
        batch_op.alter_column('island_avatar',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islands', schema=None) as batch_op:
        batch_op.alter_column('island_avatar',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('island_map')

    # ### end Alembic commands ###
