"""empty message

Revision ID: 33a1dfa5e779
Revises: 84d2e58b8693
Create Date: 2023-04-08 11:24:32.164105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a1dfa5e779'
down_revision = '84d2e58b8693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('shad', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('qid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
