"""empty message

Revision ID: 418342f51102
Revises: f788d27f161f
Create Date: 2023-02-15 09:38:49.189232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418342f51102'
down_revision = 'f788d27f161f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('islands',
    sa.Column('iuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('levels', sa.Integer(), nullable=True),
    sa.Column('problems', sa.String(length=500), nullable=True),
    sa.Column('treasure', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('iuid'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('islands')
    # ### end Alembic commands ###
