"""empty message

Revision ID: 4726e426ddec
Revises: b3a13f3139f6
Create Date: 2023-02-17 16:54:56.572746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4726e426ddec'
down_revision = 'b3a13f3139f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charge', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('charge')

    # ### end Alembic commands ###
