"""empty message

Revision ID: 4bf44b495da3
Revises: 77d18008cb5e
Create Date: 2023-02-11 19:27:56.104327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf44b495da3'
down_revision = '77d18008cb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('tuid', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=12), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=False),
    sa.Column('lname', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('students_num', sa.Integer(), nullable=True),
    sa.Column('students', sa.String(length=120), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tuid'),
    sa.UniqueConstraint('user_name')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tuid', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=12), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('lname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.Column('students_num', sa.INTEGER(), nullable=True),
    sa.Column('students', sa.VARCHAR(length=120), nullable=True),
    sa.Column('join_date', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('tuid'),
    sa.UniqueConstraint('user_name')
    )
    op.drop_table('teachers')
    # ### end Alembic commands ###
