"""empty message

Revision ID: 5338b6be5539
Revises: 33a1dfa5e779
Create Date: 2023-04-19 19:26:18.783453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5338b6be5539'
down_revision = '33a1dfa5e779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('textbook', sa.String(length=550), nullable=True))
        batch_op.add_column(sa.Column('appliance', sa.String(length=550), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_column('appliance')
        batch_op.drop_column('textbook')

    # ### end Alembic commands ###
