"""empty message

Revision ID: 68b9cd101fc0
Revises: e3b57243e50d
Create Date: 2023-04-03 12:33:20.681178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b9cd101fc0'
down_revision = 'e3b57243e50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commited', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helps', schema=None) as batch_op:
        batch_op.drop_column('commited')

    # ### end Alembic commands ###
