"""empty message

Revision ID: 6a0355f81ae3
Revises: 86318b3f972f
Create Date: 2023-04-29 12:29:27.816364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0355f81ae3'
down_revision = '86318b3f972f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('class_name')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('class_name')

    # ### end Alembic commands ###
