"""empty message

Revision ID: 7dbcb2048769
Revises: 85073b495c9b
Create Date: 2023-04-04 06:58:10.486117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbcb2048769'
down_revision = '85073b495c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passed_islands', sa.Integer(), nullable=True))
        batch_op.drop_column('open_chest')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_chest', sa.INTEGER(), nullable=True))
        batch_op.drop_column('passed_islands')

    # ### end Alembic commands ###
