"""empty message

Revision ID: 84d2e58b8693
Revises: f0a5567e7659
Create Date: 2023-04-02 14:33:28.838517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d2e58b8693'
down_revision = 'f0a5567e7659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('reward_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=550),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('reward_id',
               existing_type=sa.String(length=550),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
