"""empty message

Revision ID: 85073b495c9b
Revises: c0a9e9f7b7dd
Create Date: 2023-04-04 05:57:48.550968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85073b495c9b'
down_revision = 'c0a9e9f7b7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_waiting', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('open_chest', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('open_chest')
        batch_op.drop_column('is_waiting')

    # ### end Alembic commands ###
