"""empty message

Revision ID: 86318b3f972f
Revises: 63148512e8e5
Create Date: 2023-04-08 17:19:53.846053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86318b3f972f'
down_revision = '63148512e8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_books',
    sa.Column('tuid', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('island_id', sa.Integer(), nullable=True),
    sa.Column('lesson', sa.Integer(), nullable=True),
    sa.Column('model', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('tuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_books')
    # ### end Alembic commands ###
