"""empty message

Revision ID: 93d8d1b355d1
Revises: c94b2c040a78
Create Date: 2023-04-03 11:29:13.728450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d8d1b355d1'
down_revision = 'c94b2c040a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islands', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
