"""empty message

Revision ID: b6c425eb78a5
Revises: 02144a11c401
Create Date: 2023-02-20 15:43:36.471263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c425eb78a5'
down_revision = '02144a11c401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('levels_coord', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islands', schema=None) as batch_op:
        batch_op.drop_column('levels_coord')

    # ### end Alembic commands ###
