"""empty message

Revision ID: b7bbd317e4d5
Revises: 54fc743bbf18
Create Date: 2023-04-02 13:31:50.767942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7bbd317e4d5'
down_revision = '54fc743bbf18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rewards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('rid', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=30), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('expire_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('rid'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
