"""empty message

Revision ID: c0a9e9f7b7dd
Revises: 68b9cd101fc0
Create Date: 2023-04-03 12:34:37.782472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a9e9f7b7dd'
down_revision = '68b9cd101fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_helping', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('total_helping')

    # ### end Alembic commands ###
