"""empty message

Revision ID: c25b812d88d9
Revises: 418342f51102
Create Date: 2023-02-15 09:50:38.302968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25b812d88d9'
down_revision = '418342f51102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_book', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islands', schema=None) as batch_op:
        batch_op.drop_column('text_book')

    # ### end Alembic commands ###
