"""empty message

Revision ID: c94b2c040a78
Revises: d80664f4a4bc
Create Date: 2023-03-05 12:01:11.359007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94b2c040a78'
down_revision = 'd80664f4a4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('island_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helps', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('island_id')

    # ### end Alembic commands ###
