"""empty message

Revision ID: d3078c36003b
Revises: c25b812d88d9
Create Date: 2023-02-20 10:27:42.273289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3078c36003b'
down_revision = 'c25b812d88d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('island_avatar', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islands', schema=None) as batch_op:
        batch_op.drop_column('island_avatar')

    # ### end Alembic commands ###
