"""empty message

Revision ID: d80664f4a4bc
Revises: 18fb22117bda
Create Date: 2023-03-05 11:33:27.838719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80664f4a4bc'
down_revision = '18fb22117bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helps',
    sa.Column('huid', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('is_open', sa.Integer(), nullable=True),
    sa.Column('responser_id', sa.Integer(), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('huid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helps')
    # ### end Alembic commands ###
