"""empty message

Revision ID: dedfed553821
Revises: 7dbcb2048769
Create Date: 2023-04-05 13:11:37.486024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedfed553821'
down_revision = '7dbcb2048769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islands', schema=None) as batch_op:
        batch_op.drop_column('lesson')

    # ### end Alembic commands ###
