"""empty message

Revision ID: e3b57243e50d
Revises: 93d8d1b355d1
Create Date: 2023-04-03 11:32:34.767752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b57243e50d'
down_revision = '93d8d1b355d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clear_pass', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('just_pass', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activity', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('activity')
        batch_op.drop_column('just_pass')
        batch_op.drop_column('clear_pass')

    # ### end Alembic commands ###
