"""empty message

Revision ID: f788d27f161f
Revises: cd2a0724afdd
Create Date: 2023-02-14 19:30:20.374372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f788d27f161f'
down_revision = 'cd2a0724afdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=12), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=False),
    sa.Column('lname', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_teacher', sa.Boolean(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('students_num', sa.Integer(), nullable=True),
    sa.Column('students', sa.String(length=120), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.guid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('user_name')
    )
    op.drop_table('teachers')
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('suid', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('password', sa.VARCHAR(length=12), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('lname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.Column('join_date', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.guid'], ),
    sa.PrimaryKeyConstraint('suid'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('teachers',
    sa.Column('tuid', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=12), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('lname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.Column('students_num', sa.INTEGER(), nullable=True),
    sa.Column('students', sa.VARCHAR(length=120), nullable=True),
    sa.Column('join_date', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('tuid'),
    sa.UniqueConstraint('user_name')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
